export const titles = ["Procody X",
    "Evenner",
    "M-Dignate",
    "Boxtony",
    "Ruthfull",
    "La Facuoup",
    "Medivict",
    "Steeplump",
    "Resson",
    "Atinkers",
    "Twinhouse",
    "Lonstrian",
    "Satinge",
    "Vikins",
    "Choulder V"]